/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ModeloDao;
import entidades.Modelo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.ModeloListModel;

/**
 *
 * @author tmarc
 */
public class ifrCadastroModelo extends javax.swing.JInternalFrame {
    
    private List<Modelo> listaModelo = new ArrayList<>();
    private ModeloDao modeloDao;
    private Modelo modeloEdit;


    private ModeloListModel modeloListModel;
    private boolean edit = false;
    private int linhaSelecionada;
    private int idModelo;


    
    public ifrCadastroModelo(ModeloListModel modeloListModel, int linhaSelecionada, boolean edit, Modelo modelo){
        this.edit = edit;
        this.modeloEdit = modelo;
        this.linhaSelecionada = linhaSelecionada;
        this.modeloListModel = modeloListModel;
        initComponents();
        super.setTitle("Editar de Clientes");
        
        modeloDao = new ModeloDao();
        Modelo modeloEditar = new Modelo();
        
        modeloEditar = modeloDao.findById(modelo.getId());

        tfNome.setText(modelo.getNomeModelo());
        tfValorFipe.setText(String.valueOf(modelo.getValorFipe()));

        idModelo = modelo.getId();
    }
    
    /**
     * Creates new form ifrCadastroCliente
     */
    public ifrCadastroModelo() {
        initComponents();
        super.setTitle("Cadastro de Modelos");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNomeCompleto = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfValorFipe = new javax.swing.JTextField();
        jLabelNomeCompleto1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        jLabelNomeCompleto.setText("Nome Modelo");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfValorFipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorFipeActionPerformed(evt);
            }
        });

        jLabelNomeCompleto1.setText("Valor Fipe");

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/32x32/Hardware-Floppy-icon (Custom).png"))); // NOI18N
        btNovo.setText("Salvar");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btNovo);

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/32x32/cancel-icon (Custom).png"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        jPanel2.add(btFechar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelNomeCompleto1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeCompleto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                            .addComponent(tfValorFipe, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeCompleto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValorFipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja fechar a tela de cadastro?", "Dialog de confirmação", JOptionPane.YES_NO_CANCEL_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            super.dispose();
        }
    }//GEN-LAST:event_btFecharActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        salvar();        // TODO add your handling code here:
    }//GEN-LAST:event_btNovoActionPerformed

    private void tfValorFipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorFipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorFipeActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private Modelo getModelo() {
        Modelo modelo = new Modelo();
        modelo.setId(idModelo);
        
        
        modelo.setNomeModelo(tfNome.getText());
        modelo.setValorFipe(Double.parseDouble(tfValorFipe.getText()));

        return modelo;
    }
    
    private Modelo modelo;

    private void salvar() {
        Modelo modelo = getModelo();
        modeloDao = new ModeloDao();
        boolean retorno = false;

        if (!edit) {
            retorno = modeloDao.insert(modelo);
            
            if(retorno){
                JOptionPane.showMessageDialog(null, "Modelo inserido com sucesso. ");
            }
            
            this.dispose();
        } else {
            modelo.setId(modelo.getId());
            retorno = modeloDao.update(modelo);
            modeloListModel.atualizarModel(linhaSelecionada, modelo);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Modelo alterado com sucesso. ");
            }
            
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btNovo;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelNomeCompleto1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfValorFipe;
    // End of variables declaration//GEN-END:variables
}
