/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AutomovelDao;
import dao.ClienteDao;
import dao.ModeloDao;
import entidades.Automovel;
import entidades.Cliente;
import entidades.Modelo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.AutomovelListModel;

/**
 *
 * @author tmarc
 */
public class ifrCadastroAutomovel extends javax.swing.JInternalFrame {
    
    private List<Automovel> listaAutomoveis = new ArrayList<>();
    private ClienteDao clienteDao;
    private ModeloDao modeloDao;
    private Automovel automovelEdit;

    private AutomovelListModel automovelListModel;
    private boolean edit = false;
    private int linhaSelecionada;
    private int idAuto;



    public ifrCadastroAutomovel(AutomovelListModel automovelListModel, int linhaSelecionada, boolean edit, Automovel automovel){
        this.edit = edit;
        this.automovelEdit = automovel;
        this.linhaSelecionada = linhaSelecionada;
        this.automovelListModel = automovelListModel;
        this.idAuto = automovel.getId();

        initComponents();
        super.setTitle("Editar de Automovel");
        
        automovelDao = new AutomovelDao();
        clienteDao = new ClienteDao();
        modeloDao = new ModeloDao();
        
        Automovel automovelEditar = new Automovel();
        Cliente clienteEditar = new Cliente();
        Modelo modeloEditar = new Modelo();
        
        
        automovelEditar = automovelDao.findById(automovel.getId());
        clienteEditar = clienteDao.findById(automovel.getCliente().getId());
        modeloEditar = modeloDao.findById(automovel.getModelo().getId());


        tfAnoAutomovel.setText(String.valueOf(automovel.getAnoAutomovel()));
        tfCorAutomovel.setText(automovel.getCorAutomovel());

        clienteDao.findAll().forEach((cliente) -> {
            cbCliente.addItem(cliente);
        });
        
        modeloDao.findAll().forEach((modelo) -> {
            cbModelo.addItem(modelo);
        });
        
        System.out.println(System.getProperty("user.dir"));
    }
    
    /**
     * Creates new form ifrCadastroCliente
     */
    public ifrCadastroAutomovel() {
        initComponents();
        super.setTitle("Cadastro de Automoveis");

        clienteDao = new ClienteDao();
        clienteDao.findAll().forEach((cliente) -> {
            cbCliente.addItem(cliente);
        });
        
        modeloDao = new ModeloDao();
        modeloDao.findAll().forEach((modelo) -> {
            cbModelo.addItem(modelo);
        });

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfAnoAutomovel = new javax.swing.JTextField();
        jLabelNomeCompleto1 = new javax.swing.JLabel();
        jLabelNomeCompleto3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        cbModelo = new javax.swing.JComboBox<>();
        jLabelNomeCompleto4 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        jLabelNomeCompleto2 = new javax.swing.JLabel();
        tfCorAutomovel = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tfAnoAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnoAutomovelActionPerformed(evt);
            }
        });

        jLabelNomeCompleto1.setText("Ano Automovel");

        jLabelNomeCompleto3.setText("Modelo");

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/32x32/Hardware-Floppy-icon (Custom).png"))); // NOI18N
        btNovo.setText("Salvar");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btNovo);

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/32x32/cancel-icon (Custom).png"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        jPanel2.add(btFechar);

        cbModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModeloActionPerformed(evt);
            }
        });

        jLabelNomeCompleto4.setText("Cliente");

        jLabelNomeCompleto2.setText("Cor Automovel");

        tfCorAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCorAutomovelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNomeCompleto2)
                            .addComponent(cbCliente, 0, 460, Short.MAX_VALUE)
                            .addComponent(jLabelNomeCompleto4)
                            .addComponent(cbModelo, 0, 460, Short.MAX_VALUE)
                            .addComponent(jLabelNomeCompleto3)
                            .addComponent(jLabelNomeCompleto1)
                            .addComponent(tfAnoAutomovel)
                            .addComponent(tfCorAutomovel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeCompleto3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeCompleto4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabelNomeCompleto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAnoAutomovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeCompleto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCorAutomovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja fechar a tela de cadastro?", "Dialog de confirmação", JOptionPane.YES_NO_CANCEL_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            super.dispose();
        }
    }//GEN-LAST:event_btFecharActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        salvar();        // TODO add your handling code here:
    }//GEN-LAST:event_btNovoActionPerformed

    private void tfAnoAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnoAutomovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnoAutomovelActionPerformed

    private void cbModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModeloActionPerformed

    private void tfCorAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCorAutomovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCorAutomovelActionPerformed


    private Automovel getAutomovel() {
        Automovel automovel = new Automovel();
        automovel.setId(idAuto);
        System.out.println(tfAnoAutomovel.toString());
        automovel.setAnoAutomovel(Integer.parseInt(tfAnoAutomovel.getText()));
        
        automovel.setCorAutomovel(tfCorAutomovel.getText());
        automovel.setCliente((Cliente) cbCliente.getSelectedItem());
        automovel.setModelo((Modelo) cbModelo.getSelectedItem());

        return automovel;
    }
    
    private AutomovelDao automovelDao;
    private Automovel automovel;
    
   private void salvar() {
        Automovel auto = getAutomovel();
        automovelDao = new AutomovelDao();
        boolean retorno = false;

        if (!edit) {
            retorno = automovelDao.insert(auto);
            if(retorno){
                JOptionPane.showMessageDialog(null, "Automovel inserido com sucesso. ");
            }
            this.dispose();
        } else {
              auto.setId(auto.getId());
              retorno =automovelDao.update(auto);
              automovelListModel.atualizarModel(linhaSelecionada, auto);
              if (retorno) {
                JOptionPane.showMessageDialog(null, "Automovel alterado com sucesso. ");
            }
            
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btNovo;
    private javax.swing.JComboBox<Cliente> cbCliente;
    private javax.swing.JComboBox<Modelo> cbModelo;
    private javax.swing.JLabel jLabelNomeCompleto1;
    private javax.swing.JLabel jLabelNomeCompleto2;
    private javax.swing.JLabel jLabelNomeCompleto3;
    private javax.swing.JLabel jLabelNomeCompleto4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfAnoAutomovel;
    private javax.swing.JTextField tfCorAutomovel;
    // End of variables declaration//GEN-END:variables
}
